package nl.thk.api.config;


import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2WebMvc;

//import springfox.documentation.swagger2.annotations.EnableSwagger2;
@Slf4j
//@Configuration
//@EnableSwagger2
//@EnableSwagger2WebMvc
@Import(SpringDataRestConfiguration.class)
public class SwaggerConfig {

    // Verify http://localhost:8080/v2/api-docs <=works eventhough swagger-ui does not on spring-boot
    // http://localhost:8080/swagger-ui/ <= only works on jboss for now but this is most important as prod is jboss
    @Bean
    public Docket api() {
        log.info("DFP Configuring Swagger Config For SpringDataRestApplication2");
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }
}

// IDSME added as a reference to get swagger to work for all restpoint also generated by Spring Data Rest.
